[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"

[build.environment]
  SERVER_PRESET = "netlify_edge" # or "netlify_builder" for on-demand builders
